pre_bump_hooks = [
  # Prevent bumping from non-main branch
  """
  sh -c "if [[ \\"$(git rev-parse --abbrev-ref HEAD)\\" != \\"main\\" ]]; then echo \\"[error] you can only bump version on main branch\\"; exit 1; fi"
  """,
  "echo 'bumping from {{latest}} to {{version}}'",
  # Update crate versions
  """
  sh -c "sed -i '' -e 's/^version.*$/version = \\"{{version}}\\"/' ./thalo/Cargo.toml"
  """,
  """
  sh -c "sed -i '' -e 's/^version.*$/version = \\"{{version}}\\"/' ./thalo-inmemory/Cargo.toml"
  """,
  """
  sh -c "sed -i '' -e 's/^version.*$/version = \\"{{version}}\\"/' ./thalo-kafka/Cargo.toml"
  """,
  """
  sh -c "sed -i '' -e 's/^version.*$/version = \\"{{version}}\\"/' ./thalo-macros/Cargo.toml"
  """,
  """
  sh -c "sed -i '' -e 's/^version.*$/version = \\"{{version}}\\"/' ./thalo-postgres/Cargo.toml"
  """,
  # Update thalo dependency version in crates
  """
  sh -c "sed -i '' -e 's/^thalo [^,]*,/thalo = { version = \\"{{version}}\\",/' ./thalo-inmemory/Cargo.toml"
  """,
  """
  sh -c "sed -i '' -e 's/^thalo [^,]*,/thalo = { version = \\"{{version}}\\",/' ./thalo-kafka/Cargo.toml"
  """,
  """
  sh -c "sed -i '' -e 's/^thalo [^,]*,/thalo = { version = \\"{{version}}\\",/' ./thalo-postgres/Cargo.toml"
  """,
  """
  sh -c "sed -i '' -e 's/^thalo [^,]*,/thalo = { version = \\"{{version}}\\",/' ./thalo-testing/Cargo.toml"
  """,
  # Update thalo-macros version in thalo/Cargo.toml
  """
  sh -c "sed -i '' -e 's/^thalo-macros [^,]*,/thalo-macros = { version = \\"{{version}}\\",/' ./thalo/Cargo.toml"
  """,
  "cargo build --workspace --release",
]

post_bump_hooks = [
  "git push",
  "git push origin {{version}}",
  "echo 'publishing thalo-macros {{version}}'",
  "cargo publish -p thalo-macros",
  "sleep 10",
  "echo 'publishing thalo {{version}}'",
  "cargo publish -p thalo",
  "sleep 10",
  "echo 'publishing thalo-inmemory {{version}}'",
  "cargo publish -p thalo-inmemory",
  "echo 'publishing thalo-kafka {{version}}'",
  "cargo publish -p thalo-kafka",
  "echo 'publishing thalo-postgres {{version}}'",
  "cargo publish -p thalo-postgres",
  "echo 'publishing thalo-testing {{version}}'",
  "cargo publish -p thalo-testing",
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "thalo"
owner = "thalo-rs"
authors = [{ signature = "Ari Seyhun", username = "tqwewe" }]
