[package]
name = "awto-es"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
awto-es-macros = { path = "../awto-es-macros" }
bb8-postgres = { version = "0.7", features = ["with-serde_json-1"] }
serde = "1.0"
serde_json = "1.0"
