[package]
name = "thalo"
version = "0.2.0"
authors = ["Ari Seyhun <ariseyhun@live.com.au>"]
edition = "2021"
description = "An event sourcing & CQRS framework for Event Driven Architechture"
readme = "../README.md"
repository = "https://github.com/awto-rs/thalo"
license = "MIT OR Apache-2.0"
keywords = ["event-sourcing", "cqrs", "event-driven", "actors", "macros"]
categories = [
  "database",
  "data-structures",
  "development-tools",
  "rust-patterns",
  "web-programming::http-server",
]

[dependencies]
actix = "0.12"
async-trait = "0.1"
bb8-postgres = { version = "0.7", features = [
  "with-chrono-0_4",
  "with-serde_json-1",
  "with-uuid-0_8",
] }
chrono = "0.4"
futures = "0.3"
lru = "0.7"
once_cell = "1.8"
outbox-relay = { version = "0.1.0", path = "../outbox-relay", optional = true }
rdkafka = "0.28"
sea-query = { version = "0.19.1", features = [
  "backend-postgres",
  "postgres",
  "postgres-json",
  "thread-safe",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thalo-macros = { version = "0.2.0", path = "../thalo-macros" }
thiserror = "1.0"
tokio = { version = "1.14", features = ["macros", "sync"] }
tracing = "0.1"
typedmap = { version = "0.1", features = ["dashmap"] }

[features]
default = []
