[package]
name = "bank"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
async-trait = "0.1"
awto-es = { path = "../../awto-es" }
bb8-postgres = { version = "0.7", features = ["with-serde_json-1"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.13", features = ["macros", "rt", "rt-multi-thread"] }
