version: "3.7"
services:
  app:
    env_file:
      - app.env
    tty: true
    depends_on:
      - "redpanda"
      - "database"
    build:
      context: ../..
      dockerfile: examples/bank/app.Dockerfile
  redpanda:
    command:
      - redpanda
      - start
      - --set
      - "redpanda.auto_create_topics_enabled=true"
      - --smp
      - "1"
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    image: docker.vectorized.io/vectorized/redpanda:latest
    container_name: redpanda-1
    ports:
      - 9092:9092
      - 29092:29092
  database:
    build:
      context: .
      dockerfile: database.Dockerfile
    ports:
      - 5435:5432
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  database-data:
