[package]
name = "thaloto-kafka"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3"
futures = "0.3"
rdkafka = "0.28"
serde = "1.0"
serde_json = "1.0"
thaloto = { path = "../thaloto", features = ["event-stream"] }
thiserror = "1.0"
