[package]
name = "server"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
crossterm = "0.22"
futures-util = "0.3"
prost = "0.9"
serde_json = "1.0"
text_io = "0.1"
thaloto = { path = "../../thaloto", features = ["tests-cfg"] }
thaloto-inmemory = { path = "../../thaloto-inmemory", features = ["debug"] }
tokio = { version = "1.15", features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "sync",
] }
tonic = "0.6"

[build-dependencies]
tonic-build = "0.6"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"
