[package]
name = "example-protobuf"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.23"
futures-util = "0.3"
prost = "0.10"
serde_json = "1.0"
text_io = "0.1"
thalo = { path = "../../thalo", features = ["tests-cfg", "with-tokio-stream"] }
thalo-inmemory = { path = "../../thalo-inmemory", features = ["debug"] }
tokio = { version = "1.15", features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "sync",
] }
tokio-stream = "0.1"
tonic = "0.7"

[build-dependencies]
tonic-build = "0.7"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"
